name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.1"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wally-package-types
          version: "^1"

      - name: Download defintion files & packages
        shell: bash
        run: |
          wally install
          curl -O https://github.com/JohnnyMorganz/luau-lsp/raw/main/scripts/globalTypes.d.lua
          curl -O https://gist.github.com/zxibs/81fc195db5e0e374c63b98c262b99e1d/raw/9fa3dd6e1d9f65733c1b00fef092ecbf782b8d44/utils.d.lua
          curl -O https://gist.github.com/zxibs/1b861e0123ae548f282b106818202afd/raw/40e4e1e25f3b450c15e933fc6dd5c61192544be1/roact.d.lua
          curl -O https://gist.github.com/zxibs/92756cffe2f8ee8fe801218cb2f88931/raw/d9aeb134b8414cb161dcc838c5ce7ee10ab90f2d/unc.d.lua

      - name: Analyze
        shell: bash
        run: |
          rojo sourcemap dev.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/
          cat globalTypes.d.lua utils.d.lua roact.d.lua unc.d.lua loaded.d.lua > definitions.d.lua
          echo definitions.d.lua
          luau-lsp analyze --no-strict-dm-types --ignore=Packages/** --base-luaurc=.luaurc --sourcemap=sourcemap.json --definitions=definitions.d.lua src/
        